- name: Check/Install git,python3,venv
  hosts: all

  tasks:
  - name: Install and/or update git
    ansible.builtin.package:
      name: git
      state: latest

  - name: Install and/or update python3-venv
    ansible.builtin.package:
      name: python3-venv
      state: latest

  - name: Install and/or update python3
    ansible.builtin.package:
      name: python3
      state: latest